// ── JI Scale Data (41-EDO Pythagorean + 53-EDO Schismatic) ────────────────
//
// Step values for the 19 curated JI scales the Tonal Audiation tabs
// expose under Pythagorean and Schismatic temperaments.  Each scale's
// degree → step map is computed from the underlying just-intonation
// ratios converted to the nearest integer step in 41-EDO and 53-EDO.
//
// The names here match the public tonality identifiers in
// jiTonalityFamilies.ts.  A module-load side-effect registers these maps
// with edoData.ts so getModeDegreeMap() returns them, mirroring how the
// septimal/neutral/etc. xen families are wired in for 31-EDO.
//
// Where multiple JI ratios round to the same EDO step, we pick the
// theoretically-cleaner ratio (e.g. 5/4 over 81/64 for the 5-limit M3).
// 41-EDO and 53-EDO both round these consistently — the differences in
// chord/scale character come from elsewhere.

import { registerXenPatternMaps } from "./edoData";

type ModeMap = Record<string, number>;
type ScaleFamilyMap = Record<string, ModeMap>;

// ── JI Scale catalog ─────────────────────────────────────────────────────
//
// Each entry lists [degree-label, ratio-cents] tuples.  We compute the
// EDO-specific step at scale-build time by rounding cents to the nearest
// step.  Keeping the cents alongside the labels makes the music-theory
// intent traceable; if a ratio later needs adjusting, the change is in
// one place.
//
// Cents reference (for grep / sanity-check):
//   1/1     0          12/11   150.6      14/9    764.9
//   16/15   111.7      11/9    347.4      8/5     813.7
//   10/9    182.4      5/4     386.3      18/11   852.6
//   9/8     203.9      81/64   407.8      5/3     884.4
//   7/6     266.9      4/3     498.0      27/16   905.9
//   32/27   294.1      11/8    551.3      12/7    933.1
//   6/5     315.6      45/32   590.2      7/4     968.8
//                      7/5     582.5      16/9    996.1
//                      729/512 611.7      9/5     1017.6
//                      3/2     701.96     11/6    1049.4
//                                         15/8    1088.3
//                                         243/128 1109.8

interface JiScaleSpec {
  name: string;
  /** [degree label, cents] tuples sorted ascending by cents. */
  steps: [string, number][];
}

const JI_SCALES: JiScaleSpec[] = [
  // ── 3-LIMIT (Pythagorean) ────────────────────────────────────────────
  // Generated by stacks of pure 3:2 fifths; thirds are 81/64 (Pyth M3) or
  // 32/27 (Pyth m3).
  { name: "Pythagorean Ionian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["7",1109.8]] },
  { name: "Pythagorean Aeolian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["b6",792.2],["b7",996.1]] },
  { name: "Pythagorean Dorian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },
  { name: "Pythagorean Mixolydian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },

  // ── 5-LIMIT (Just Intonation) ────────────────────────────────────────
  // Pure 5/4 thirds; modes use the "tonally-pure" form where each mode's
  // tonic has a true 3/2 fifth (so the 2nd of Dorian is 10/9, not 9/8 —
  // avoids the wolf 5th that mode-of-Ionian-via-rotation would introduce).
  { name: "JI Ionian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Dorian",
    steps: [["1",0],["2",182.4],["b3",315.6],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Phrygian",
    steps: [["1",0],["b2",111.7],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Lydian",
    steps: [["1",0],["2",203.9],["3",386.3],["#4",590.2],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Mixolydian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Aeolian",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Harmonic Minor",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["7",1088.3]] },

  // ── 7-LIMIT (Septimal) ───────────────────────────────────────────────
  // Adds 7/4 (harmonic 7th, ~969¢), 7/6 (subminor 3rd, ~267¢),
  // 7/5 (septimal tritone, ~583¢).  Garibaldi[7] is the 7-note MOS
  // generated by the 4/3 generator in 41-EDO (and same in 53-EDO).
  { name: "Garibaldi",
    // 41-EDO: stacks of 17\41 mod 41 → sorted [0,3,10,17,20,27,34]
    // 53-EDO: stacks of 22\53 mod 53 → sorted [0,4,13,22,26,35,44]
    // Cents here are taken from the 41-EDO realisation; 53-EDO rounds the
    // same chromatic positions to its own grid via the catalog mechanism.
    steps: [["1",0],["b2",87.8],["b3",292.7],["4",497.6],["#4",585.4],["b6",790.2],["b7",995.1]] },
  { name: "Septimal Major",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",968.8]] },
  { name: "Septimal Minor",
    steps: [["1",0],["2",203.9],["b3",266.9],["4",498.0],["5",702.0],["b6",813.7],["b7",968.8]] },
  { name: "Septimal Diminished",
    steps: [["1",0],["2",203.9],["b3",266.9],["4",498.0],["b5",582.5],["b6",813.7],["b7",968.8]] },

  // ── 11-LIMIT (Neutral / Maqam) ───────────────────────────────────────
  // Adds 11/9 (neutral 3rd, ~347¢), 11/8 (wide 4th, ~551¢), 12/11
  // (neutral 2nd, ~151¢).  Mohajira is the canonical neutral diatonic
  // (LsLsLsL where s is a neutral 2nd).  The Maqam scales mix neutral
  // intervals with diatonic ones in the patterns that define each maqam.
  { name: "Mohajira",
    steps: [["1",0],["b2",150.6],["b3",347.4],["4",498.0],["5",702.0],["b6",852.6],["b7",1049.4]] },
  { name: "Maqam Rast",
    steps: [["1",0],["2",203.9],["b3",347.4],["4",498.0],["5",702.0],["6",905.9],["b7",1049.4]] },
  { name: "Maqam Bayati",
    steps: [["1",0],["b2",150.6],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Hijaz",
    // Two augmented seconds — characteristic Hijaz "exotic" sound.
    steps: [["1",0],["b2",111.7],["3",386.3],["4",498.0],["5",702.0],["b6",813.7],["b7",996.1]] },
];

// ── Build per-EDO ScaleFamilyMaps ────────────────────────────────────────
//
// edoData's getModeDegreeMap looks up scales as
//   maps[scaleFam]?.[modeName]
// so we group every JI scale under one synthetic family per EDO ("JI
// Family") and key by the scale's display name.  The bank/picker code in
// jiTonalityFamilies.ts surfaces them through the limit groups; the
// underlying lookup just needs the map.

const JI_FAMILY_NAME = "JI Family";

function centsToStep(cents: number, edo: number): number {
  return Math.round((cents / 1200) * edo);
}

function buildJiScalesForEdo(edo: number): ScaleFamilyMap {
  const fam: Record<string, ModeMap> = {};
  for (const scale of JI_SCALES) {
    const map: ModeMap = {};
    for (const [degLabel, cents] of scale.steps) {
      map[degLabel] = centsToStep(cents, edo);
    }
    fam[scale.name] = map;
  }
  return { [JI_FAMILY_NAME]: fam };
}

// ── Module-load registration ────────────────────────────────────────────
// Side-effect: hooks the JI families into edoData's pattern-map cache so
// getModeDegreeMap(41, "JI Family", "Pythagorean Ionian") returns the
// degree map without any further wiring.  Mirrors the 31-EDO xen
// registration in musicTheory.ts.

registerXenPatternMaps(41, buildJiScalesForEdo(41));
registerXenPatternMaps(53, buildJiScalesForEdo(53));

// ── Public helpers ──────────────────────────────────────────────────────

/** Family name used for all JI scales (single bucket per EDO). */
export const JI_FAMILY = JI_FAMILY_NAME;

/** Flat list of every JI scale name in catalog order. */
export const JI_SCALE_NAMES: string[] = JI_SCALES.map(s => s.name);

/** Steps for a JI scale in a given EDO, sorted ascending. */
export function getJiScaleSteps(edo: number, scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, cents]) => centsToStep(cents, edo));
}

/** Degree labels for a JI scale, in scale order. */
export function getJiScaleDegrees(scaleName: string): string[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([deg]) => deg);
}
