// ── JI Scale Data (41-EDO Pythagorean + 53-EDO Schismatic) ────────────────
//
// Step values for the 19 curated JI scales the Tonal Audiation tabs
// expose under Pythagorean and Schismatic temperaments.  Each scale's
// degree → step map is computed from the underlying just-intonation
// ratios converted to the nearest integer step in 41-EDO and 53-EDO.
//
// The names here match the public tonality identifiers in
// jiTonalityFamilies.ts.  A module-load side-effect registers these maps
// with edoData.ts so getModeDegreeMap() returns them, mirroring how the
// septimal/neutral/etc. xen families are wired in for 31-EDO.
//
// Where multiple JI ratios round to the same EDO step, we pick the
// theoretically-cleaner ratio (e.g. 5/4 over 81/64 for the 5-limit M3).
// 41-EDO and 53-EDO both round these consistently — the differences in
// chord/scale character come from elsewhere.

import { registerXenPatternMaps } from "./edoData";
import { registerScaleCents } from "./jiChordAnalysis";

type ModeMap = Record<string, number>;
type ScaleFamilyMap = Record<string, ModeMap>;

// ── JI Scale catalog ─────────────────────────────────────────────────────
//
// Each entry lists [degree-label, ratio-cents] tuples.  We compute the
// EDO-specific step at scale-build time by rounding cents to the nearest
// step.  Keeping the cents alongside the labels makes the music-theory
// intent traceable; if a ratio later needs adjusting, the change is in
// one place.
//
// Cents reference (for grep / sanity-check):
//   1/1     0          12/11   150.6      14/9    764.9
//   16/15   111.7      11/9    347.4      8/5     813.7
//   10/9    182.4      5/4     386.3      18/11   852.6
//   9/8     203.9      81/64   407.8      5/3     884.4
//   7/6     266.9      4/3     498.0      27/16   905.9
//   32/27   294.1      11/8    551.3      12/7    933.1
//   6/5     315.6      45/32   590.2      7/4     968.8
//                      7/5     582.5      16/9    996.1
//                      729/512 611.7      9/5     1017.6
//                      3/2     701.96     11/6    1049.4
//                                         15/8    1088.3
//                                         243/128 1109.8

interface JiScaleSpec {
  name: string;
  /** [degree label, cents] tuples sorted ascending by cents. */
  steps: [string, number][];
}

const JI_SCALES: JiScaleSpec[] = [
  // ── 3-LIMIT (Pythagorean) ────────────────────────────────────────────
  // Generated by stacks of pure 3:2 fifths; thirds are 81/64 (Pyth M3) or
  // 32/27 (Pyth m3).
  { name: "Pythagorean Ionian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["7",1109.8]] },
  { name: "Pythagorean Aeolian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["b6",792.2],["b7",996.1]] },
  { name: "Pythagorean Dorian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },
  { name: "Pythagorean Mixolydian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },

  // ── 5-LIMIT (Just Intonation) ────────────────────────────────────────
  // Pure 5/4 thirds; modes use the "tonally-pure" form where each mode's
  // tonic has a true 3/2 fifth (so the 2nd of Dorian is 10/9, not 9/8 —
  // avoids the wolf 5th that mode-of-Ionian-via-rotation would introduce).
  { name: "JI Ionian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Dorian",
    steps: [["1",0],["2",182.4],["b3",315.6],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Phrygian",
    steps: [["1",0],["b2",111.7],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Lydian",
    steps: [["1",0],["2",203.9],["3",386.3],["#4",590.2],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Mixolydian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Aeolian",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Harmonic Minor",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["7",1088.3]] },

  // ── 7-LIMIT (Septimal) ───────────────────────────────────────────────
  // Adds 7/4 (harmonic 7th, ~969¢), 7/6 (subminor 3rd, ~267¢),
  // 7/5 (septimal tritone, ~583¢).  Garibaldi[7] is the 7-note MOS
  // generated by the 4/3 generator in 41-EDO (and same in 53-EDO).
  { name: "Garibaldi",
    // 41-EDO: stacks of 17\41 mod 41 → sorted [0,3,10,17,20,27,34]
    // 53-EDO: stacks of 22\53 mod 53 → sorted [0,4,13,22,26,35,44]
    // Cents here are taken from the 41-EDO realisation; 53-EDO rounds the
    // same chromatic positions to its own grid via the catalog mechanism.
    steps: [["1",0],["b2",87.8],["b3",292.7],["4",497.6],["#4",585.4],["b6",790.2],["b7",995.1]] },
  { name: "Septimal Major",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",968.8]] },
  { name: "Septimal Minor",
    // Canonical 1-b3-5 (1, 9/8, 6/5, 4/3, 3/2) so the I chord reads as a
    // true minor triad (lowercase i).  The 7-prime colour lives at the
    // b7 (7/4) — the modal-defining tone where the 7-limit sound bites.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",968.8]] },
  { name: "Septimal Diminished",
    steps: [["1",0],["2",203.9],["b3",266.9],["4",498.0],["b5",582.5],["b6",813.7],["b7",968.8]] },
  { name: "Septimal Lydian",
    // 5-limit Lydian spine; #4 lifts to 7/5 (~582¢) — septimal tritone,
    // sharper and more "blue" than the 5-limit 45/32.
    steps: [["1",0],["2",203.9],["3",386.3],["#4",582.5],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "Septimal Phrygian",
    // Phrygian darkness with 7-limit b3 (7/6 ≈ 267¢) — recognisable as
    // Phrygian but with a "subminor" colour at the third.
    steps: [["1",0],["b2",111.7],["b3",266.9],["4",498.0],["5",702.0],["b6",813.7],["b7",968.8]] },

  // ── 11-LIMIT (Neutral / Maqam) ───────────────────────────────────────
  // Adds 11/9 (neutral 3rd, ~347¢), 11/8 (wide 4th, ~551¢), 12/11
  // (neutral 2nd, ~151¢).  Mohajira is the canonical neutral diatonic
  // (LsLsLsL where s is a neutral 2nd).  The Maqam scales mix neutral
  // intervals with diatonic ones in the patterns that define each maqam.
  { name: "Mohajira",
    steps: [["1",0],["b2",150.6],["b3",347.4],["4",498.0],["5",702.0],["b6",852.6],["b7",1049.4]] },
  { name: "Maqam Rast",
    steps: [["1",0],["2",203.9],["b3",347.4],["4",498.0],["5",702.0],["6",905.9],["b7",1049.4]] },
  { name: "Maqam Bayati",
    steps: [["1",0],["b2",150.6],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Hijaz",
    // Two augmented seconds — characteristic Hijaz "exotic" sound.
    steps: [["1",0],["b2",111.7],["3",386.3],["4",498.0],["5",702.0],["b6",813.7],["b7",996.1]] },
  // Additional 11-limit Maqamat — both feature the 11/8 wide 4th or
  // 11-prime-derived intervals that don't reduce cleanly to lower limits.
  { name: "Maqam Saba",
    // Saba's hallmark is the dropped 4th (here 11/8 wide instead of 4/3)
    // creating an unstable, longing colour.  Common in Iraqi / Egyptian Maqam.
    steps: [["1",0],["2",203.9],["b3",315.6],["#4",551.3],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Huzam",
    // Built on Sikah; uses a neutral 3rd (11/9) and a wide minor 6th (11/7).
    steps: [["1",0],["b2",165.0],["b3",347.4],["4",498.0],["5",702.0],["b6",782.5],["b7",1017.6]] },
  { name: "Maqam Nahawand",
    // 5-limit Aeolian / natural minor as Maqam — included here because
    // the Maqam tradition treats it as one of its own, with subtle
    // 11-limit inflections in performance practice (the tonic chord
    // can take the 11-limit neutral 9th as a colour tone).
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Kurd",
    // Phrygian-flavoured Maqam — 5-limit b2 anchor with neutral 3 and
    // 11-limit b6 at 11/7.
    steps: [["1",0],["b2",111.7],["b3",315.6],["4",498.0],["5",702.0],["b6",782.5],["b7",1017.6]] },
  { name: "Maqam Nikriz",
    // Augmented-second Maqam (cousin of Hijaz, distinct in its 4 and 6).
    // Uses 11-limit colour in upper tetrachord.
    steps: [["1",0],["2",203.9],["b3",315.6],["#4",582.5],["5",702.0],["6",884.4],["b7",1017.6]] },

  // ── 13-LIMIT (Tridecimal) ────────────────────────────────────────────
  // Per direct user direction (2026-05-04): a "13-limit Major" / "Minor"
  // chord keeps its canonical 1-3-5 quality (5/4 M3 for Major, 6/5 m3
  // for Minor, 3/2 P5 throughout) so the I chord reads as a true major
  // (uppercase I) or minor (lowercase i) triad.  The 13-prime colour
  // lives in the upper modal-defining tones (the 6th and 7th), which
  // is what marks the scale as 13-limit rather than its 5-limit cousin.
  // Key 13-prime intervals: 13/12 (138¢), 13/11 (289¢ supraminor 3rd),
  // 13/10 (454¢ supermajor 3rd), 13/9 (637¢ aug-4th), 13/8 (841¢ wide
  // M6 / neutral 6), 13/7 (1072¢ subminor 7th).
  { name: "Tridecimal Major",
    // 3 → 5/4 (canonical major 3rd, 5-prime ratio is allowed in 13-limit
    // since 5 < 13), 6 → 13/8 (841¢), 7 → 13/7 (1072¢).  The two upper
    // tones carry the 13-prime; the triad stays cleanly major.
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",840.5],["7",1071.7]] },
  { name: "Tridecimal Minor",
    // b3 → 6/5 (canonical minor 3rd), b6 → 13/8, b7 → 13/7.  Tonic
    // triad reads as a clean minor; 13-prime colours only the upper
    // modal tones.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",840.5],["b7",1071.7]] },
  { name: "Maqam Sikah",
    // The neutral 3rd / 6th Maqam family Sikah belongs to.  In 13-limit
    // the b3 (16/13 ≈ 359¢) sits a touch lower than the 11-limit
    // neutral 3rd (11/9 ≈ 347¢), giving a darker, more melodic colour.
    steps: [["1",0],["2",203.9],["b3",359.5],["4",498.0],["5",702.0],["b6",840.5],["b7",1049.4]] },
  { name: "Maqam Awj Iraq",
    // 13-limit Iraqi Maqam — named for the "Awj" (apex) tone in the upper
    // tetrachord.  Uses 16/13 (~359¢) as the neutral 3rd plus 13/9
    // (~637¢) as a tridecimal augmented-4th alternative; closes with
    // 13/8 (~841¢) at the 6th.  Distinct from Sikah in its sharpened 4.
    steps: [["1",0],["2",203.9],["b3",359.5],["#4",636.6],["5",702.0],["b6",840.5],["b7",996.1]] },
  { name: "Tridecimal Lydian",
    // Lydian variant — the #4 (13/9 ≈ 637¢) is the Lydian-defining
    // tone and is itself a 13-prime interval, so it stays in even
    // though normally the 4 would be anchored.  The 6 also takes 13/8.
    steps: [["1",0],["2",203.9],["3",386.3],["#4",636.6],["5",702.0],["6",840.5],["7",1088.3]] },

  // ── 17-LIMIT (Heptadecimal) ──────────────────────────────────────────
  // Key 17-prime intervals: 17/16 (105¢ small leading-tone m2),
  // 17/14 (336¢ supraminor 3rd), 17/13 (464¢ wide M3), 17/12 (603¢
  // tritone), 17/11 (754¢ b6), 17/10 (919¢ wide M6), 17/9 (1101¢
  // wide M7).
  { name: "Heptadecimal Major",
    // 3 → 5/4 (canonical major 3rd), 6 → 17/10, 7 → 17/9.  Triad
    // stays canonically major (uppercase I); 17-prime colour lives in
    // the upper tetrachord (M6 + M7).
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",918.6],["7",1101.0]] },
  { name: "Heptadecimal Minor",
    // b3 → 6/5 (canonical minor 3rd), b2 → 17/16, b6 → 17/11, b7 →
    // 17/10.  Triad reads as a clean minor (lowercase i); 17-prime
    // colours the b2 and the upper tetrachord.
    steps: [["1",0],["b2",105.0],["b3",315.6],["4",498.0],["5",702.0],["b6",753.6],["b7",918.6]] },
  { name: "Heptadecimal Hijaz",
    // Hijaz spine — major-mode tonic triad.  b2 → 17/16, 3 → 5/4
    // (canonical M3 — keeps the I chord cleanly major), b6 → 17/11.
    // 17-prime tones colour the b2 and b6 (Hijaz-defining tones).
    steps: [["1",0],["b2",105.0],["3",386.3],["4",498.0],["5",702.0],["b6",753.6],["b7",996.1]] },

  // ── 19-LIMIT (Nonadecimal) ───────────────────────────────────────────
  // Key 19-prime intervals: 19/18 (94¢ small m2), 19/16 (298¢ m3),
  // 19/15 (409¢ wide M3), 19/13 (657¢ #4-area), 19/12 (795¢ b6-ish),
  // 19/11 (946¢ b7), 19/10 (1111¢ wide M7).
  { name: "Nonadecimal Major",
    // 3 → 5/4 (canonical M3 — keeps tonic triad cleanly major).
    // 6 → 19/12 (795¢, leans b6, so this is a Mixolydian-b6-flavoured
    // Major), 7 → 19/10.  19-prime colour lives in the upper tetrachord.
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["b6",795.0],["7",1111.2]] },
  { name: "Nonadecimal Minor",
    // b3 → 6/5 (canonical minor 3rd), b6 → 19/12, b7 → 19/11.  Tonic
    // triad reads as a clean minor (lowercase i); 19-prime colours the
    // b6 and b7.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",795.0],["b7",945.7]] },

  // ── 23 / 29 / 31-LIMIT (multi-prime higher-limit colour) ─────────────
  // Same rule as 13 / 17 / 19-limit: tonic triad stays canonical
  // (1, 5/4 or 6/5 third, 3/2 fifth) so the I roman numeral renders
  // correctly as I (Major) or i (Minor).  The named prime colours the
  // upper modal tones — 6 and b7 / 7 — where the higher-prime sound
  // bites without compromising the chord quality.
  // 41-EDO approximates each prime to within a few cents; 53-EDO is
  // accurate on 13 / 19 and weaker on 17 / 23 / 29 / 31, which is why
  // those scales aren't surfaced for 53-EDO in JI_LIMITS_PER_EDO.

  // 23-LIMIT  Key intervals: 23/22 (77¢ b2), 23/19 (329¢ supraminor 3),
  //          23/18 (424¢ wide M3), 23/14 (859¢ b6), 23/12 (1126¢
  //          extra-wide M7).  No clean 23-prime M6 or b7.
  { name: "Vicesimotertial Major",
    // 3 → 5/4 (canonical M3 — keeps tonic triad cleanly major).
    // 6 → 23/14 (859¢), 7 → 23/12 (1126¢).  23-prime colour in the
    // upper tetrachord.
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",859.4],["7",1126.3]] },
  { name: "Vicesimotertial Minor",
    // b3 → 6/5 (canonical m3 — keeps tonic triad cleanly minor).
    // b6 → 23/14 (859¢), b7 → 23/13 (988¢).  23-prime colour in the
    // upper modal tones.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",859.4],["b7",987.7]] },
  // 29-LIMIT  Key intervals: 29/27 (124¢ small m2), 29/24 (328¢
  //          supraminor 3rd), 29/23 (401¢ wide M3), 29/18 (770¢ b6),
  //          29/17 (871¢ M6), 29/16 (1030¢ b7).  No clean 29-prime M7
  //          — Major-mode 7 falls back to 15/8 OR Major adopts a
  //          Mixolydian b7 to fit a 29-prime tone there.
  { name: "Vicenovenal Major",
    // 3 → 5/4 (canonical M3 — keeps tonic triad cleanly major).
    // 6 → 29/17 (871¢), b7 → 29/16 (1030¢, Mixolydian-leaning).
    // 29-prime colour in the upper tetrachord.
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",871.4],["b7",1029.6]] },
  { name: "Vicenovenal Minor",
    // b3 → 6/5 (canonical m3 — keeps tonic triad cleanly minor).
    // b6 → 29/18 (770¢), b7 → 29/16 (1030¢).  29-prime colour in the
    // upper modal tones.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",770.5],["b7",1029.6]] },
  // 31-LIMIT  Key intervals: 31/29 (115¢ b2), 31/26 (336¢ supraminor 3),
  //          31/25 (372¢ neutral-leaning M3), 31/20 (765¢ b6),
  //          31/19 (905¢ M6), 31/17 (1010¢ b7), 31/16 (1145¢ extra-
  //          wide M7).
  { name: "Trigesimoprimal Major",
    // 3 → 5/4 (canonical M3 — keeps tonic triad cleanly major).
    // 6 → 31/19 (905¢), 7 → 31/16 (1145¢ extra-wide leading-tone).
    // 31-prime colour in the upper tetrachord.
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",904.6],["7",1145.0]] },
  { name: "Trigesimoprimal Minor",
    // b3 → 6/5 (canonical m3 — keeps tonic triad cleanly minor).
    // b6 → 31/20 (765¢), b7 → 31/17 (1010¢).  31-prime colour in the
    // upper modal tones.
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",765.5],["b7",1010.4]] },
];

// ── Build per-EDO ScaleFamilyMaps ────────────────────────────────────────
//
// edoData's getModeDegreeMap looks up scales as
//   maps[scaleFam]?.[modeName]
// so we group every JI scale under one synthetic family per EDO ("JI
// Family") and key by the scale's display name.  The bank/picker code in
// jiTonalityFamilies.ts surfaces them through the limit groups; the
// underlying lookup just needs the map.

const JI_FAMILY_NAME = "JI Family";

function centsToStep(cents: number, edo: number): number {
  return Math.round((cents / 1200) * edo);
}

function buildJiScalesForEdo(edo: number): ScaleFamilyMap {
  const fam: Record<string, ModeMap> = {};
  for (const scale of JI_SCALES) {
    const map: ModeMap = {};
    for (const [degLabel, cents] of scale.steps) {
      map[degLabel] = centsToStep(cents, edo);
    }
    fam[scale.name] = map;
  }
  return { [JI_FAMILY_NAME]: fam };
}

// ── Module-load registration ────────────────────────────────────────────
// Side-effect: hooks the JI families into edoData's pattern-map cache so
// getModeDegreeMap(41, "JI Family", "Pythagorean Ionian") returns the
// degree map without any further wiring.  Mirrors the 31-EDO xen
// registration in musicTheory.ts.

registerXenPatternMaps(41, buildJiScalesForEdo(41));
registerXenPatternMaps(53, buildJiScalesForEdo(53));

// Cent-value side-channel for the chord analyzer — avoids a circular
// import by letting jiChordAnalysis.ts pull the underlying cents
// without re-importing JI_SCALES.
for (const scale of JI_SCALES) {
  registerScaleCents(scale.name, scale.steps.map(([, c]) => c));
}

// ── Public helpers ──────────────────────────────────────────────────────

/** Family name used for all JI scales (single bucket per EDO). */
export const JI_FAMILY = JI_FAMILY_NAME;

/** Flat list of every JI scale name in catalog order. */
export const JI_SCALE_NAMES: string[] = JI_SCALES.map(s => s.name);

/** Steps for a JI scale in a given EDO, sorted ascending. */
export function getJiScaleSteps(edo: number, scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, cents]) => centsToStep(cents, edo));
}

/** Degree labels for a JI scale, in scale order. */
export function getJiScaleDegrees(scaleName: string): string[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([deg]) => deg);
}

/** Cent values for a JI scale, in scale order.  Useful for the lattice
 *  viewer which projects exact cents onto the (3,5) lattice rather than
 *  rounding through any specific EDO grid. */
export function getJiScaleCents(scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, c]) => c);
}
